---
apiVersion: v2
appVersion: 1.7.1
description: A Helm chart for installing PrivateBin
name: privatebin
home: https://privatebin.info/
icon: https://raw.githubusercontent.com/PrivateBin/assets/master/images/preview/icon.png
type: application
version: 0.21.1
maintainers:
  - name: bdashrad
    email: bdashrad@gmail.com
sources:
  - https://github.com/PrivateBin/PrivateBin
  - https://github.com/PrivateBin/docker-nginx-fpm-alpine
keywords:
  - pastebin
  - PrivateBin
  - ZeroBin
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Upgrade PrivateBin to 1.7.1
  artifacthub.io/images: |
    - name: privatebin
      image: privatebin/nginx-fpm-alpine:1.7.1
